// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLxICd1YapR6k3rDmgjQ9qoMoroediX1Q',
    appId: '1:895534940106:android:e86c4990c1e963037a5933',
    messagingSenderId: '895534940106',
    projectId: 'quizee-759e9',
    storageBucket: 'quizee-759e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBRIavu4fTfCm0MH9zNOrE4tdqAsIdI8k',
    appId: '1:895534940106:ios:a345b93ccc194bf37a5933',
    messagingSenderId: '895534940106',
    projectId: 'quizee-759e9',
    storageBucket: 'quizee-759e9.appspot.com',
    androidClientId: '895534940106-vr42tne0mm050gapfh5kall68kejgol4.apps.googleusercontent.com',
    iosClientId: '895534940106-14l2arhjfojuflteiihf988ousv5nmgt.apps.googleusercontent.com',
    iosBundleId: 'com.aba.quizee',
  );
}
