// ignore_for_file: must_be_immutable

import 'package:flutter/material.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class UiDesign extends StatelessWidget {
  const UiDesign({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: ListView(children: [
          OptionContainer(),
        ]),
      ),
    );
  }
}

class OptionContainer extends StatelessWidget {
  late String text;
  bool isChosen = false;
  OptionContainer({ this.text = ''});
  @override
  Widget build(BuildContext context) {
    return Container(
      width: MediaQuery.of(context).size.width,
      height: 67,
      decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
      child: Row(
        children: [
          Container(
            width: 47,
            height: 47,
            decoration: ShapeDecoration(
              color: Color(0xFF606060),
              shape: OvalBorder(),
            ),
          ),
        ],
      ),
    );
  }
}


///

                          
                                         